# Generated by Django 6.0.6 on 2026-06-22 14:35

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('domain', 'Domain'), ('subdomain', 'Subdomain'), ('ip_address', 'IP Address'), ('service', 'Service'), ('certificate', 'Certificate'), ('technology', 'Technology')], db_index=True, max_length=20)),
                ('value', models.CharField(db_index=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('stale', 'Stale'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('import', 'Import'), ('scan', 'Scan'), ('manual', 'Manual')], max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='tenants.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('resolves_to', 'Resolves To'), ('belongs_to', 'Belongs To'), ('runs_service', 'Runs Service'), ('covers', 'Covers'), ('detected_on', 'Detected On')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='assets.asset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='tenants.organization')),
                ('to_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='assets.asset')),
            ],
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'type', 'status'], name='assets_asse_organiz_f300af_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('organization', 'type', 'value'), name='unique_org_type_value'),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('from_asset', 'to_asset', 'relationship_type'), name='unique_relationship'),
        ),
    ]
