# Generated by Django 6.0.6 on 2026-06-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rejectedrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ['-created_at']},
        ),
    ]
